### PR TITLE
Disable auto-detect for BurntToast

### LINKED ISSUE #18: BurntToast causes auto-detect to be very slow on Windows
I found `maven-notifier` to be very slow on Windows 10 with default configuration (ie no config). Maven commands which had taken about 1 second started taking about 10 seconds, and I eventually traced it to `BurntToastNotifier.tryInit`. (I didn't have BurntToast installed.)

I just installed BurntToast to see if `Get-Module -ListAvailable -Name BurntToast | Format-Table Name` could detect it faster, and I think it's far too slow to activate automatically.

Would you accept a PR to remove BurntToast from the automatic detection in `NotifierProvider.available()`?

### PR DESCRIPTION
**Pull request by seanf**
fixes #18

### CODE REVIEW

**Comment by seanf** [comment]
@jcgay I have fixed the failing test, but Travis is still failing, apparently because of a missing Sonar server.

**Comment by jcgay** [comment]
Ok Thank you ! I'll have à look quickly 👍

Le mar. 9 avr. 2019 à 09:08, Sean Flanigan <notifications@github.com> a
écrit :

**Comment by jcgay** [comment]
Thanks again for the patch 👍

**Comment by seanf** [comment]
Thanks @jcgay, any chance of a release for send-notification and maven-notifier?

**Comment by jcgay** [comment]
Sure, I'll do it today!

**Comment by jcgay** [comment]
Done, should be synced in Maven central in a few minutes :)

**Comment by seanf** [comment]
Excellent, thanks @jcgay !

**Pull request closed without merging**
